spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/funintodo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: set1-server
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: set2-server
server:
  port: 8082

---
spring:
  profiles:
    group:
      set1: set1-server, real-db
      set2: set2-server, real-db